environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_x64: "C:\\Python27-x64"
    - PYTHON: "C:\\Python27-x64"
      PYTHON_x64: "C:\\Python27-x64"
    - PYTHON: "C:\\Python39"
      PYTHON_x64: "C:\\Python39-x64"
cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
install:
  - '%PYTHON%\python -m virtualenv venv'
  - '.\venv\Scripts\pip install --upgrade "setuptools<45.0.0" -r requirements.txt nose'
build_script:
#  - '.\venv\Scripts\python setup.py build_ext --inplace'
  - '.\venv\Scripts\python setup.py bdist_wheel'

  - 'cd matlab_proxy'
  - '%PYTHON_x64%\python -m virtualenv venv'
  - '.\venv\Scripts\pip install -r requirements.txt'
  - '.\venv\Scripts\python setup.py py2exe'
  - '.\venv\Scripts\python setup.py bdist_wheel -p win32'
  - 'rd /s/q build'
  - '.\venv\Scripts\python setup.py bdist_wheel'
  - 'cd ..'
  
after_build:
  - ps: Get-ChildItem dist\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName matlab_wrapper }
  - ps: Get-ChildItem matlab_proxy\dist\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName matlab_proxy }
test_script:
  - '.\venv\Scripts\nosetests'
#  nosetests.exe --with-coverage --cover-html --traverse-namespace --cover-branches --cover-erase --cover-tests
#  coverage html -d cover

deploy:
  - provider: GitHub
    artifact: /.*.whl/
    draft: false
    prerelease: false
    auth_token:
      secure: 6Eoe7p9mqStkqanseUsqMedSW6iSeR58OIaqbmDGAnsitnL5gstRs2MqBwjFKBUq
    on:
      appveyor_repo_tag: true
  - provider: S3
    access_key_id: AKIAJCSEQOUWIU2HK3SQ
    secret_access_key:
      secure: gKHiok/Emkvb298mPcxWXTn2ttSFnRTEmsaTYex3qZlqHSRVptKjvD2bVeA4XJ7a
    bucket: pypi.metamorphsoftware.com
    region: us-east-1
    artifact: matlab_wrapper
    folder: matlab-wrapper
    on:
      appveyor_repo_tag: true
  - provider: S3
    access_key_id: AKIAJCSEQOUWIU2HK3SQ
    secret_access_key:
      secure: gKHiok/Emkvb298mPcxWXTn2ttSFnRTEmsaTYex3qZlqHSRVptKjvD2bVeA4XJ7a
    bucket: pypi.metamorphsoftware.com
    region: us-east-1
    artifact: matlab_proxy
    folder: matlab-proxy
    on:
      appveyor_repo_tag: true
