environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
install:
  - '%PYTHON%\python -m virtualenv venv'
  - '.\venv\Scripts\pip install --upgrade -r requirements.txt nose'
build_script:
#  - '.\venv\Scripts\python setup.py build_ext --inplace'
  - '.\venv\Scripts\python setup.py bdist_wheel'
after_build:
  - ps: Get-ChildItem dist\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test_script:
  - '.\venv\Scripts\nosetests'
#  nosetests.exe --with-coverage --cover-html --traverse-namespace --cover-branches --cover-erase --cover-tests
#  coverage html -d cover
#deploy:
#  - provider: GitHub
#    artifact: 'dist\*.whl'
#    draft: false
#    prerelease: false
#    auth_token:
#      secure: yFXzatuZuCoIHQ1VmlpfLPND2jGU4l1NHkNUfoLXrrTfo5m7VxYJNGiXp7OnpCgp
#    on:
#      appveyor_repo_tag: true
