environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_MAJOR: 2
    - PYTHON: "C:\\Python39"
      PYTHON_MAJOR: 3
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: "C:\\Python310"
      PYTHON_MAJOR: 3
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: "C:\\Python311"
      PYTHON_MAJOR: 3
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'
install:
  - '%PYTHON%\python -m virtualenv venv'
  - '.\venv\Scripts\pip install --extra-index-url https://pypi.metamorphsoftware.com -r requirements.txt pytest'
build_script:
  - '.\venv\Scripts\python setup.py bdist_wheel'

  - 'cd matlab_proxy'

  - if %PYTHON_MAJOR% == 3 ( C:\Python37-x64\python -m virtualenv env_37_x64 && .\env_37_x64\Scripts\python -m pip install six py2exe && .\env_37_x64\Scripts\python setup.py py2exe || exit 1)
  - if %PYTHON_MAJOR% == 3 ( C:\Python39-x64\python -m virtualenv venv && .\venv\Scripts\python -m pip install six py2exe && .\venv\Scripts\python setup.py py2exe || exit 1)

  - if %PYTHON_MAJOR% == 2 ( C:\Python27-x64\python -m virtualenv venv && .\venv\Scripts\python -m pip install --extra-index-url https://pypi.metamorphsoftware.com/ six py2exe && .\venv\Scripts\python setup.py py2exe || exit 1)

  - '.\venv\Scripts\pip install -r requirements.txt'
  - '.\venv\Scripts\python setup.py bdist_wheel -p win32'
  - 'rd /s/q build'
  - '.\venv\Scripts\python setup.py bdist_wheel'
  - 'cd ..'

after_build:
  - ps: Get-ChildItem dist\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName matlab_wrapper }
  - ps: Get-ChildItem matlab_proxy\dist\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName matlab_proxy }
test_script:
  - 'set PYTHONPATH=%CD%\matlab_proxy'
  - '.\venv\Scripts\pytest'
#  nosetests.exe --with-coverage --cover-html --traverse-namespace --cover-branches --cover-erase --cover-tests
#  coverage html -d cover

deploy:
  - provider: GitHub
    artifact: /.*.whl/
    draft: false
    prerelease: false
    auth_token:
      # metamorph-jenkins matlab_wrapper-appveyor
      secure: cmbLPoKTtlQRfTodhYgt7ltVCSkgo6E38sNgVo6vV0kKuXTP6Q4zvocsjenRJgZa
    on:
      appveyor_repo_tag: true
  - provider: S3
    access_key_id: AKIAJCSEQOUWIU2HK3SQ
    secret_access_key:
      secure: gKHiok/Emkvb298mPcxWXTn2ttSFnRTEmsaTYex3qZlqHSRVptKjvD2bVeA4XJ7a
    bucket: pypi.metamorphsoftware.com
    region: us-east-1
    artifact: matlab_wrapper
    folder: matlab-wrapper
    on:
      appveyor_repo_tag: true
  - provider: S3
    access_key_id: AKIAJCSEQOUWIU2HK3SQ
    secret_access_key:
      secure: gKHiok/Emkvb298mPcxWXTn2ttSFnRTEmsaTYex3qZlqHSRVptKjvD2bVeA4XJ7a
    bucket: pypi.metamorphsoftware.com
    region: us-east-1
    artifact: matlab_proxy
    folder: matlab-proxy
    on:
      appveyor_repo_tag: true
